#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>

#define SOCKET_FILE "./uds_endpoint.socket"
#define BUFFER_SIZE 1024

int main() {
    int client_fd;
    struct sockaddr_un server_addr;
    char buffer[BUFFER_SIZE];

    // 1. Create socket client
    client_fd = socket(AF_UNIX, SOCK_STREAM, 0);
    if (client_fd == -1) {
        perror("[-] Error al crear el socket");
        exit(EXIT_FAILURE);
    }
    
    // 2. Config memory addr struct
    memset(&server_addr, 0, sizeof(struct sockaddr_un));
    server_addr.sun_family = AF_UNIX;
    strncpy(server_addr.sun_path, SOCKET_FILE, sizeof(server_addr.sun_path) - 1);

    printf("[*] Intentando conectar a %s...\n", SOCKET_FILE);

    // 3. Connect to server 
    if (connect(client_fd, (struct sockaddr *) &server_addr, sizeof(struct sockaddr_un)) == -1) {
        perror("[-] Error al conectar. ¿Está el servidor corriendo?");
        close(client_fd);
        exit(EXIT_FAILURE);
    }

    printf("[+] Conectado exitosamente al servidor.\n");
    printf("[!] Escribe tu mensaje o 'SALIR' para desconectar.\n\n");

    // Chat loop
    while(1) {
        printf("Tú: ");
        
        // 4. Get input from user via terminal
        memset(buffer, 0, BUFFER_SIZE);
        if (fgets(buffer, BUFFER_SIZE, stdin) == NULL) {
            break;
        }

        // Clean newline character generated by fgets
        buffer[strcspn(buffer, "\n")] = 0;

        // Prevent sending empty lines
        if (strlen(buffer) == 0) {
            continue;
        }

        // 5. Send message 
        write(client_fd, buffer, strlen(buffer));

        // If user typed 'SALIR', break the loop after notifying server (case-insensitive)
        if (strcasecmp(buffer, "SALIR") == 0) {
            printf("[-] Desconectando del servidor...\n");
            break;
        }

        // 6. Read server response
        memset(buffer, 0, BUFFER_SIZE);
        read(client_fd, buffer, BUFFER_SIZE - 1);
        printf("[Servidor responde]: %s\n", buffer);
    }
    // 7. Close socket connection
    close(client_fd);

    return 0;
}